item {
id: 1
name: 'toilet'
}
item {
id: 2
name: 'swimming pool'
}
item {
id: 3
name: 'bed'
}
item {
id: 4
name: 'billiard table'
}
item {
id: 5
name: 'sink'
}
item {
id: 6
name: 'fountain'
}
item {
id: 7
name: 'oven'
}
item {
id: 8
name: 'ceiling fan'
}
item {
id: 9
name: 'television'
}
item {
id: 10
name: 'microwave oven'
}
item {
id: 11
name: 'gas stove'
}
item {
id: 12
name: 'refrigerator'
}
item {
id: 13
name: 'kitchen & dining room table'
}
item {
id: 14
name: 'washing machine'
}
item {
id: 15
name: 'bathtub'
}
item {
id: 16
name: 'stairs'
}
item {
id: 17
name: 'fireplace'
}
item {
id: 18
name: 'pillow'
}
item {
id: 19
name: 'mirror'
}
item {
id: 20
name: 'shower'
}
item {
id: 21
name: 'couch'
}
item {
id: 22
name: 'countertop'
}
item {
id: 23
name: 'coffeemaker'
}
item {
id: 24
name: 'dishwasher'
}
item {
id: 25
name: 'sofa bed'
}
item {
id: 26
name: 'tree house'
}
item {
id: 27
name: 'towel'
}
item {
id: 28
name: 'porch'
}
item {
id: 29
name: 'wine rack'
}
item {
id: 30
name: 'jacuzzi'
}
